server:
  port: 8189
  servlet:
    context-path: /mysecurity
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=mysecurity
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  flyway:
    baseline-on-migrate: true

